### ISSUE TITLE
The types field is wrong in package.json

### ISSUE THREAD

**Issue by cncolder** [infinitered/reactotron-core-client#155]
The `types` field is "dist/types/reactotron-core-client.d.ts".
https://unpkg.com/browse/reactotron-core-client@2.8.6/package.json

But the real path is "dist/types/src/reactotron-core-client.d.ts".
https://unpkg.com/browse/reactotron-core-client@2.8.6/dist/types/src/reactotron-core-client.d.ts

**Comment by rmevans9** [comment]
That shouldn’t be. Something must have changed the path where the types are. I’ll look to sort this out asap

**Comment by cncolder** [comment]
A temporary solution:

```ts
// Put this `reactotron-core-client.d.ts` in your source folder.

declare module 'reactotron-core-client' {
    import { Reactotron } from 'reactotron-core-client/dist/types/src/reactotron-core-client'

    export { Reactotron }
}
```
